routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::redirect('/', '/posts');
Route::resource('posts', 'PostController');
Route::resource('categories', 'CategoryController');

Route::post('/search', 'CategoryController@search')
    ->name('categories.search');

Route::name('comments.')
    ->prefix('comments')
    ->middleware('auth')
    ->group(function () {

        Route::post('/', 'CommentController@store')
            ->name('store');
        Route::delete('/{comment}', 'CommentController@destroy')
            ->name('destroy');

    });

Route::post('/posts/{post}/views/count', 'ViewController@count')
    ->name('posts.views.count');
Route::post('/posts/view/{post}', 'ViewController@addView')
    ->name('posts.addView');

app/Models/Post.php
<?php

namespace App\Models;

use App\Models\Traits\HasComments;
use App\User;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasComments;

    protected $fillable = [
        'title', 'content', 'user_id'
    ];

    function user() {
        return $this->belongsTo(User::class);
    }
    function views() {
        return $this->hasOne(View::class);
    }
    function categories() {
        return $this->belongsToMany(Category::class);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\User;
use Illuminate\Http\Request;
use App\Models\Post;
use Illuminate\Support\Facades\Auth;
use function GuzzleHttp\Promise\all;

class PostController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except(['index', 'show']);
    }

    public function index()
    {
        $user = Auth::user();
        if($user){
            $isAuthor = $user->isAuthor;
        }
        else{
            $isAuthor = 0;
        }
        return view('posts.index', [
            'title' => 'Blog',
            'posts' => Post::all(),
            'isAuthor' => $isAuthor
        ]);
    }

    public function create()
    {
        $categories = Category::all();
        return view('posts.form', [
            'title' => 'New post',
            'categories' => $categories
        ]);
    }

    protected function rules() {
        return [
            'title' => 'required|min:5',
            'content' => 'required|min:10'
        ];
    }

    public function store(Request $request)
    {
        $request->validate($this->rules());

        $data = $request->except('_token');
        $user = auth()->user();
        $post = $user->posts()->create($data);
        if(isset($request->category)){
            foreach ($request->category as $category){
                $post->categories()->attach($category);
            }
        }

        return redirect()->route('posts.show', $post);
    }

    public function show(Post $post)
    {
        $user = Auth::user();
        if($user){
            $isAuthor = $user->isAuthor;
        }
        else{
            $isAuthor = 0;
        }
        return view('posts.show', [
            'title' => $post->title,
            'post' => $post,
            'isAuthor' => $isAuthor
        ]);
    }

    public function edit(Post $post)
    {
        $this->authorize('update', $post);
        $categories = Category::all();
        $postCategories = $post->categories()->pluck('category_id');
        return view('posts.form', [
            'title' => 'Edit ' . $post->title,
            'post' => $post,
            'categories' => $categories,
            'postCategories' => $postCategories
        ]);
    }

    public function update(Request $request, Post $post)
    {
        $this->authorize('update', $post);
        $request->validate($this->rules());

        $data = $request->except(['_token', '_method', 'category']);
        $post->fill($data);
        $post->categories()->detach();
        if(isset($request->category)){
            foreach ($request->category as $category){
                $post->categories()->attach($category);
            }
        }
        $post->save();

        return redirect()->route('posts.show', $post);
    }

    public function destroy(Post $post)
    {
        $this->authorize('delete', $post);
        $post->delete();
        return redirect()->route('posts.index');
    }
}

resources/views/posts/_partials/actions.blade.php
<?php
use Illuminate\Support\Str;
$id = Str::random(10);
?>

<div class="mb-3 m-5 btn-group btn-group-lg">

    @if ($isAuthor)
        <a class="btn btn-info" href="{{ route('posts.edit', $post) }}">
            Edit
        </a>
    @endif

    @if ($isAuthor)
        <a class="btn btn-danger" id="{{ $id }}" href="{{ route('posts.destroy', $post) }}" data-target="delete-{{ $id }}">
            Delete
        </a>
    @endif

</div>

@if ($isAuthor)

    <form id="delete-{{ $id }}" action="{{ route('posts.destroy', $post) }}" method="POST" class="d-none">
        @csrf
        @method('DELETE')
    </form>

    <script>
        let link = document.getElementById('{{ $id }}');
        if (link) {
            let id = link.dataset.target;
            link.addEventListener('click', function (event) {
                event.preventDefault();
                let form = document.getElementById(id);
                form.submit();
            });
        }
    </script>

@endif

resources/views/posts/_partials/comment.blade.php
<?php
use Illuminate\Support\Str;
$id = Str::random();
?>

<div class="card mb-3 m-5 @if($active ?? false) bg-secondary text-white @endif">

    @if ($post ?? false)
        <a href="{{ route('posts.show', $comment->post) }}" class="card-header">{{ $comment->post->title }}</a>
    @endif

    <div class="card-body">
        {{ $comment->content }}
    </div>

    <small class="card-footer d-flex align-items-center">

        <span>{{$comment->user->name}}</span>
        <span class="ml-auto">{{ $comment->created_at }}</span>

        @if($comment->user_id == optional(auth()->user())->id)

            <a href="{{ route('comments.destroy', $comment) }}"
               class="btn btn-outline-danger border-0 btn-sm ml-2"
               id="comment-delete-{{ $id }}"
               data-target="comment-delete-{{$comment->id}}">
                Удалить
            </a>
            <form id="comment-delete-{{$comment->id}}" action="{{ route('comments.destroy', $comment) }}"
                  method="POST">
                @csrf @method('DELETE')
            </form>

        @endif

    </small>

</div>

@if($comment->user_id == optional(auth()->user())->id)
    <script>
        let deleteLink = document.getElementById('comment-delete-{{ $id }}');
        deleteLink.addEventListener('click', function (event) {
            event.preventDefault();
            let target = deleteLink.dataset.target;
            let form = document.getElementById(target);
            form.submit();
        });
    </script>
@endif

resources/views/posts/_partials/comment_form.blade.php
<form action="{{ route('comments.store') }}" method="POST" class="mb-3 m-5">

    @csrf

    <input type="hidden" name="post_id" value="{{ $post->id }}">
    <label for="content">Comments</label>

    @error('content')
    <div class="alert alert-danger mb-3">
        Comment can not be empty
    </div>
    @enderror

    <textarea name="content" id="content" class="form-control" placeholder="Your comment..."></textarea>

    <div>
        <button class="btn btn-secondary mt-2 btn-sm">Send</button>
    </div>

</form>

resources/views/posts/_partials/comments_block.blade.php
@forelse($post->comments as $comment)

    @component('posts._partials.comment', [
        'comment' => $comment,
        'active' => $comment->user_id === optional(auth()->user())->id
    ])@endcomponent

@empty

    <div class="alert alert-secondary m-5">
        There are no comments yet. You can be first
    </div>

@endforelse

resources/views/posts/_partials/like_button.blade.php
<?php
use Illuminate\Support\Str;
$id = Str::random();
?>

<div class="d-flex">
    <span id="view-{{ $id }}" class="ml-auto text-black-50">
        Views: <span class="count"></span>
    </span>
</div>

<script>
    function updateLikesCount(view) {
        axios.post( '{{ route('posts.views.count', $post) }}' ).then(function (res) {
            let count = res.data['count'];
            let span = view.querySelector('span');
            span.innerHTML = count;
        });
    }
    let view = document.getElementById('view-{{ $id }}');
    window.onload = function() {
        axios.post( '{{ route('posts.addView', $post) }}' ).then(function (response) {
            let data = response.data;
            if (data.status === 200) {
                updateLikesCount(view);
            }
        });
    };
</script>

resources/views/posts/_partials/post_block.blade.php
<div class="card card-body m-5 mb-auto">

    <h1>{{ $post->title }}</h1>
    <p class="lead">{{ $post->content }}</p>

    {{ $slot }}

</div>

resources/views/posts/_partials/search.blade.php
<form action="{{ route('categories.search') }}" method="POST" role="search">
    {{ csrf_field() }}
    <div class="input-group d-flex flex-column form-group">
        <label for="searchText" class="col-form-label ">You can search post by category</label>
        <input type="text"
               class="form-control @error('searchText') is-invalid @enderror form-control-lg align-baseline"
               name="searchText"
               id="searchText"
               placeholder="Enter category name...">
        <button type="submit" class="btn btn-default card justify-content-around text-center btn-outline-dark">
            <span class="text-center text-black-50">Search</span>
        </button>
        @error('searchText')
        <div class="invalid-feedback">
            {{ $message }}
        </div>
        @enderror
    </div>
</form>