routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::redirect('/', '/posts');
Route::resource('posts', 'PostController');
Route::resource('categories', 'CategoryController');

Route::post('/search', 'CategoryController@search')
    ->name('categories.search');

Route::name('comments.')
    ->prefix('comments')
    ->middleware('auth')
    ->group(function () {

        Route::post('/', 'CommentController@store')
            ->name('store');
        Route::delete('/{comment}', 'CommentController@destroy')
            ->name('destroy');

    });

Route::post('/posts/{post}/views/count', 'ViewController@count')
    ->name('posts.views.count');
Route::post('/posts/view/{post}', 'ViewController@addView')
    ->name('posts.addView');

app/Models/Post.php
<?php

namespace App\Models;

use App\Models\Traits\HasComments;
use App\User;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasComments;

    protected $fillable = [
        'title', 'content', 'user_id'
    ];

    function user() {
        return $this->belongsTo(User::class);
    }
    function views() {
        return $this->hasOne(View::class);
    }
    function categories() {
        return $this->belongsToMany(Category::class);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\User;
use Illuminate\Http\Request;
use App\Models\Post;
use Illuminate\Support\Facades\Auth;
use function GuzzleHttp\Promise\all;

class PostController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except(['index', 'show']);
    }

    public function index()
    {
        $user = Auth::user();
        if($user){
            $isAuthor = $user->isAuthor;
        }
        else{
            $isAuthor = 0;
        }
        return view('posts.index', [
            'title' => 'Blog',
            'posts' => Post::all(),
            'isAuthor' => $isAuthor
        ]);
    }

    public function create()
    {
        $categories = Category::all();
        return view('posts.form', [
            'title' => 'New post',
            'categories' => $categories
        ]);
    }

    protected function rules() {
        return [
            'title' => 'required|min:5',
            'content' => 'required|min:10'
        ];
    }

    public function store(Request $request)
    {
        $request->validate($this->rules());

        $data = $request->except('_token');
        $user = auth()->user();
        $post = $user->posts()->create($data);
        if(isset($request->category)){
            foreach ($request->category as $category){
                $post->categories()->attach($category);
            }
        }

        return redirect()->route('posts.show', $post);
    }

    public function show(Post $post)
    {
        $user = Auth::user();
        if($user){
            $isAuthor = $user->isAuthor;
        }
        else{
            $isAuthor = 0;
        }
        return view('posts.show', [
            'title' => $post->title,
            'post' => $post,
            'isAuthor' => $isAuthor
        ]);
    }

    public function edit(Post $post)
    {
        $this->authorize('update', $post);
        $categories = Category::all();
        $postCategories = $post->categories()->pluck('category_id');
        return view('posts.form', [
            'title' => 'Edit ' . $post->title,
            'post' => $post,
            'categories' => $categories,
            'postCategories' => $postCategories
        ]);
    }

    public function update(Request $request, Post $post)
    {
        $this->authorize('update', $post);
        $request->validate($this->rules());

        $data = $request->except(['_token', '_method', 'category']);
        $post->fill($data);
        $post->categories()->detach();
        if(isset($request->category)){
            foreach ($request->category as $category){
                $post->categories()->attach($category);
            }
        }
        $post->save();

        return redirect()->route('posts.show', $post);
    }

    public function destroy(Post $post)
    {
        $this->authorize('delete', $post);
        $post->delete();
        return redirect()->route('posts.index');
    }
}

resources/views/posts/form.blade.php
<?php
$update = isset($post);
?>

@extends('layouts.app')

@section('content')
    <h1 class="m-5">{{ $title }}</h1>
    <form action="{{ $update ? route('posts.update', $post) : route('posts.store') }}" method="POST" class="card card-body m-5">
        @csrf
        @if ($update)
            @method('PUT')
        @endif
        <div class="form-group">
            <label for="title">Title <span class="text-danger">*</span></label>
            <input type="text"
                   name="title"
                   id="title"
                   class="form-control @error('title') is-invalid @enderror"
                   placeholder="Enter title..."
                   value="{{ old('title') ?? ($post->title ?? '') }}">
            @error('title')
            <div class="invalid-feedback">
                {{ $message }}
            </div>
            @enderror
        </div>

        <div class="form-group">
            <label for="content">Post <span class="text-danger">*</span></label>
            <textarea name="content"
                      id="content"
                      class="form-control @error('content') is-invalid @enderror"
                      placeholder="Enter text...">{{ old('content') ?? ($post->content ?? '') }}</textarea>
            @error('content')
            <div class="invalid-feedback">
                {{ $message }}
            </div>
            @enderror
        </div>

        <div class="form-group">
            <label for="category">Category</label>
            <select name="category[]" id="category" multiple class="custom-select-sm align-bottom w-25 form-control" >
                @foreach($categories as $category)
                    <option class="form-text form-control"
                            value="{{ $category->id }}"
                            @if(isset($postCategories) && in_array($category->id, $postCategories->toArray())) selected @endif>{{ $category->name }}</option>
                @endforeach
            </select>
        </div>

        <div>
            <button class="btn btn-success">{{ $update ? 'Update' : 'Add' }}</button>
        </div>

    </form>

@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="d-flex align-items-center justify-content-between m-5">
        <h1>{{ $title }}</h1>
        @component('posts._partials.search')@endcomponent
        @if ($isAuthor)
            <div>
                <a href="{{ route('posts.create') }}" class="btn btn-success ml-auto">
                    Create post
                </a>
                <a href="{{ route('categories.create') }}" class="btn btn-success ml-auto">
                    Create category
                </a>
            </div>
        @endif
    </div>

    @forelse($posts as $post)
        <a href="{{ route('posts.show', $post) }}" class="mb-3 m-5 card card-body d-flex flex-column align-items-start">
            <h4 class="mb-0">{{ $post->title }}</h4>
            <div class="d-flex align-items-baseline mt-5">
                <h6>Categories:</h6>
                @foreach($post->categories as $category)
                    <span class="ml-2 bg-light card text-black-50">{{$category->name}}</span>
                @endforeach
            </div>
        </a>
    @empty
        <div class="m-5 alert alert-secondary">
            No posts yet...
        </div>
    @endforelse

@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('content')

    @if ($isAuthor)

        @component('posts._partials.actions', [ 'post' => $post, 'isAuthor' => $isAuthor ])@endcomponent

    @endif

    @component('posts._partials.post_block', ['post' => $post])

        @component('posts._partials.like_button', ['post' => $post])@endcomponent

    @endcomponent

    @if (auth()->check())

        @component('posts._partials.comment_form', [ 'post' => $post ])@endcomponent

    @endif

    @component('posts._partials.comments_block', [ 'post' => $post ])@endcomponent


@endsection