routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::redirect('/', '/posts');
Route::resource('posts', 'PostController');
Route::resource('categories', 'CategoryController');

Route::post('/search', 'CategoryController@search')
    ->name('categories.search');

Route::name('comments.')
    ->prefix('comments')
    ->middleware('auth')
    ->group(function () {

        Route::post('/', 'CommentController@store')
            ->name('store');
        Route::delete('/{comment}', 'CommentController@destroy')
            ->name('destroy');

    });

Route::post('/posts/{post}/views/count', 'ViewController@count')
    ->name('posts.views.count');
Route::post('/posts/view/{post}', 'ViewController@addView')
    ->name('posts.addView');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        'name'
    ];

    function post() {
        return $this->belongsToMany(Post::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CategoryController extends Controller
{
    public function create()
    {
        return view('categories.form', [
            'title' => 'New category'
        ]);
    }
    protected function rules() {
        return [
            'searchText' => 'required|min:3'
        ];
    }
    protected function rulesForCategory() {
        return [
            'name' => 'required|min:3'
        ];
    }
    public function search(Request $request)
    {
        $request->validate($this->rules());
        $searchText = $request->searchText;
        $categoryIds = Category::query()->where('name', 'like', "%{$searchText}%")->pluck('id');
        $postsIds = Post::query()
            ->join('category_post', 'id', '=','category_post.post_id')
            ->whereIn('category_post.category_id', $categoryIds)->select('id')->groupBy('id')->pluck('id');
        $posts = Post::query()->whereIn('id', $postsIds)->get();
        return view('categories.index', [
            'title' => 'Search result for ' . $searchText,
            'posts' => $posts
        ]);
    }

    public function store(Request $request)
    {
        $request->validate($this->rulesForCategory());
        $data = $request->except('_token');
        $newCategory = new Category();
        $newCategory->name = $data['name'];
        $newCategory->save();

        return redirect()->route('posts.index');
    }
}

resources/views/categories/form.blade.php
@extends('layouts.app')

@section('content')
    <h1 class="m-5">{{ $title }}</h1>
    <form action="{{ route('categories.store') }}" method="POST" class="card card-body m-5">
        @csrf
        <div class="form-group">
            <label for="name">Name <span class="text-danger">*</span></label>
            <input type="text"
                   name="name"
                   id="name"
                   class="form-control @error('name') is-invalid @enderror"
                   placeholder="Enter title..."
                   value="{{ old('title') }}">
            @error('name')
            <div class="invalid-feedback">
                {{ $message }}
            </div>
            @enderror
        </div>

        <div>
            <button class="btn btn-success">Add</button>
        </div>

    </form>

@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="d-flex align-items-center justify-content-between m-5">
        <h1>{{ $title }}</h1>
        @component('posts._partials.search')@endcomponent
    </div>

    @forelse($posts as $post)
        <a href="{{ route('posts.show', $post) }}" class="mb-3 m-5 card card-body d-flex flex-column align-items-start">
            <h4 class="mb-0">{{ $post->title }}</h4>
            <div class="d-flex align-items-baseline mt-5">
                <h6>Categories:</h6>
                @foreach($post->categories as $category)
                    <span class="ml-2 bg-light card text-black-50">{{$category->name}}</span>
                @endforeach
            </div>
        </a>
    @empty
        <div class="m-5 alert alert-secondary">
            No posts yet...
        </div>
    @endforelse

@endsection